# Generated by Django 3.1.3 on 2021-05-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginStateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_state', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'login_state',
            },
        ),
    ]
