# Generated by Django 3.1.3 on 2021-03-29 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gameinfo',
            table='douban_game',
        ),
    ]
