# Generated by Django 3.1.3 on 2021-04-16 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel_rank', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zonghengmodel',
            old_name='bookinfo',
            new_name='info',
        ),
    ]
