# Generated by Django 3.1.3 on 2021-04-30 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel_rank', '0003_auto_20210420_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChuangShiModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top', models.IntegerField(null=True)),
                ('bookname', models.CharField(max_length=150, null=True)),
                ('click', models.IntegerField(null=True)),
                ('info', models.CharField(max_length=500, null=True)),
                ('label', models.CharField(max_length=200, null=True)),
                ('type', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'chuangshi',
                'ordering': ['id'],
            },
        ),
    ]
